apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: 1-java-quarkus
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: appstudio
  namespace: rhn-support-djodha
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
status: {}
